# Generated by Django 4.0 on 2022-09-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grades',
        ),
        migrations.AddField(
            model_name='student',
            name='grades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.grade'),
        ),
    ]
